// SPDX-License-Identifier: Apache-2.0
syntax = "proto3";

package skyproto.mohair;

import "google/protobuf/any.proto";
import "skyproto/substrait/algebra.proto";
import "skyproto/substrait/type.proto";

/*
 * [SkyRel]
 * where a catalog name is resolved to physical data. If naming a partition or slice
 * directly in a query, it is better to be explicit with `SkyPartitionRel` and
 * `SkySliceRel`. If a catalog lookup is expected, it may be useful to use `SkyRel`.
 *
 * SkyRel with no slices specified (slices().empty()) represents a full scan; otherwise,
 * it is a partial scan of specific slices (or "data pages"). Although indices are
 * physically represented as a `size_t`, a uint32 satisfies practical naming requirements.
 * Specifically, 24 bits can enumerate all blocks on a 16 TiB medium, assuming 1 MiB
 * blocks:
 *
 *     (2 ** 44) - (2 ** 20) = (2 ** 24)
 *
 * Hints and statistics provided with SkyRel messages can be handled at any intermediate
 * CSE and potentially propagated to a leaf-level CSE (located on a CSD).
 *
 * [SkySliceRel]
 * specifies a slice (logical or physical) that should be directly retrieved
 * (bypass the catalog) using the `slice_key`. A slice corresponds to the smallest unit of
 * object storage (named in the object storage system namespace).
 *
 * A partition that is stored as a single slice can be represented by a SkySliceRel by
 * setting the slice_key to the resolved name of the slice; this avoids the indirection
 * that would be otherwise required (a meta slice and a data slice).
 */


// >> Utility types

//! Metadata for mohair services to communicate platform information.
//  This allows upstream services to adapt future splitting strategies for pushdown plans.
message ExecutionStats {
  optional double runtime  = 1;
}


// >> Types to support cooperative decomposition

//! A reference to a relation in a SuperPlan where data should flow to.
//  NOTE: Merging requires a SuperPlan message be propagated with resulting pushback plan.
message SuperPlan {
  // Contextual information for the leaf Rel of the super plan
  skyproto.substrait.Rel merge_rel = 1;

  // Reference to the leaf Rel of the super plan
  uint32 mergerel_reference = 2;

  // Reference to the PlanRel of the super plan
  uint32 superplan_reference = 3;
}

//! A reference to the root relation in a SubPlan
message SubPlan {
  // Information of the root Rel of the sub plan
  skyproto.substrait.Rel split_rel = 1;

  // Reference to the PlanRel of the sub plan
  uint32 subplan_reference = 2;
}


// >> Relation types (can be packed into an appropriate Extension type of substrait)

//! Placeholder for a plan subtree that could not be parsed by a preceding service.
message QueryRel {
  bytes query = 1;
}

//! An error state that should be communicated to subsequent services.
message ErrRel {
  string  err_msg  = 1;
  ErrType err_code = 2;

  enum ErrType {
    INVALID_MSG_TYPE = 0;
  }
}

//! Logical relation corresponding to a skytether partition managed by a database catalog.
//  Used for catalog systems that support extensions or custom storage interfaces.
message SkyRel {
  string domain    = 1;
  string partition = 2;
}

//! A logical or physical partition that is not managed by a database catalog.
message SkyPartitionRel {
  string domain    = 1;
  string partition = 2;

  repeated uint32 slices = 3;
}

//! A logical or physical slice that is not managed by a database catalog.
message SkySliceRel {
  // The full key name of the slice; not just the index of the slice in the partition.
  string slice_key = 1;
  string domain    = 2;
  string partition = 3;
  uint32 slice     = 4;
}

//! Materialized result set that needs to be requested from the service
message SkyResultRel {
  string result_name      = 1;
  string service_location = 2;

  skyproto.substrait.RelCommon   common = 3;
  skyproto.substrait.NamedStruct schema = 4;

  optional ExecutionStats execstats = 5;
}

//! Destination for the result set to be pushed into
message SkyLakeRel {
  uint64   context_id = 1;
  optional ExecutionStats execstats = 2;
}
