// SPDX-License-Identifier: Apache-2.0
syntax = "proto3";

package skyproto.mohair;

import "google/protobuf/any.proto";


// ------------------------------
// Message structures

// >> Hardware resource descriptions

//! Available compute resources of a "platform" a service is running on.
message CpuSpec {
  repeated float  core_freqs    = 1;
  repeated uint32 cache_sizes   = 2;
  optional uint32 count_threads = 3;

  //! Coarse-grain categories of computational storage devices.
  enum DeviceClass {
    SERVER = 0;
    DRIVE  = 1;
    SOC    = 2;
    ARRAY  = 3;
    DPU    = 4;
  }
}

//! Available memory resources of a "platform" a service is running on.
message MemorySpec {
  uint32              count_mebibytes = 1;
  optional MemoryType memory_type     = 2;
  optional uint32     memory_freq     = 3;
  optional uint32     count_channels  = 4;

  //! Coarse-grain categories of memory subsystem types.
  enum MemoryType {
    DDR  = 0;
    GDDR = 1;
    NVM  = 2;
    CXL  = 3;
    CAM  = 4;
  }
}

//! A single message containing various information about the computing platform.
message PlatformSpec {
  repeated CpuSpec    cpu_info = 1;
  repeated MemorySpec mem_info = 2;
}


// >> Cooperative decomposition configurations

//! Strategy for choosing a query split for decomposition.
enum DecomposeAlg {
  None             = 0; // Do not split plan (propagation only)
  LongPipelineLeaf = 1; // Leaf pipeline breaker with longest pipeline
  LongPipelineHead = 2; // Internal pipeline breaker with longest pipeline
  TallJoinLeaf     = 3; // Leaf join operation with tallest plan height
  WideJoinHead     = 4; // Internal join operation with largest plan width
  Eager            = 5; // Annotation to split eagerly
}


// >> Service configurations

//! A service that participates in the computational storage system.
message ServiceConfig {
  bool   is_active = 1;
  string label     = 2;
  string location  = 3;

  optional DecomposeAlg  decompose_alg    = 4;
  optional PlatformSpec  service_platform = 5;
  repeated ServiceConfig downstream       = 6;
}

